### ISSUE TITLE
README - error in system env variable names - `GAS_TIP_CAP` or `TIP`?

### ISSUE THREAD

**Issue by cmjc** [autonity/autonity-oracle#21]
## Summary

The CLI flag name for the tip config property is `tip`. The section https://github.com/autonity/autonity-oracle?tab=readme-ov-file#system-environment-variables has `GAS_TIP_CAP`.

Should that be `TIP`, or is this just inconsistent naming?

**Comment by Jason-Zhangxin-Chen** [comment]
@cmjc `GAS_TIP_CAP` is more meaningful, let's keep it on purpose.
