### ISSUE TITLE
Games R4 feedback

### ISSUE THREAD

**Issue by lorenzo-dev1** [autonity/autonity-oracle#3]
I have setup a oracle server running along a validator node. I have some feedback and some questions on the oracle. @Jason-Zhangxin-Chen 

## questions

~I launched my oracle server, however from the logs I cannot understand if it is actually fetching the prices or if it is stuck. Does the node print some logs if it is fetching the price correctly?~

~When I try to terminate the process with CTRL+C, the oracle is unresponsive, thus I believe there is some issue going on.~

~oracle version: built from commit 84ec4ed9c58aca34e10638200ce5ccfa3161d049~

~command: `./autoracle -oracle_key_file="${HOME}/.autonity/keystore/UTC--2023-11-20T12-51-55.981678000Z--ffcfb6811b81eef05c86dcbf99136bbf3d4f656b" -oracle_key_password="" -oracle_autonity_ws_url="ws://127.0.0.1:8546" -oracle_plugin_conf="${HOME}/plugins/plugins-conf.yml" -oracle_plugin_dir="${HOME}/plugins" 2>&1 | tee oracle.log`~

~log (taken around 17:13, so 10 minutes passed from the last log print): [oracle.log](https://github.com/autonity/autonity-oracle/files/13417769/oracle.log)~

Edit: I was using the wrong version of the autonity oracle, with the [v0.12.1 version](https://github.com/autonity/autonity-oracle/releases/tag/v0.1.2) the price reporting works.

Following feedback is still valid.

## feedback

If launched without any arguments, the oracle client panics with error:
```
panic: invalid key file: ./test_data/keystore/UTC--2023-02-27T09-10-19.592765887Z--b749d3d83376276ab4ddef2d9300fb5ce70ebafe
```
It would be better to handle failure gracefully / print the help text.

Some feedback on the oracle options (e.g. `-oracle_key_file`, `-oracle_key_password`, etc.)
- it would be better to have the `--` prefix for long names and the `-` for the abbreviations (or do not support abbreviations). 
- I think that the`oracle` prefix to all the options can be removed, it is redundant.
- we should probably substitute the `_` in the options with `.` (that's the convention we use in the autonity client) and try to keep the options keywords as concise as possible, to facilitate usage.
- I think that the default values might have potential for improvement. Right now they make sense if you compiled from source (e.g. default value for `-oracle_plugin_dir="./build/bin/plugins"`). However I think that we have to consider how people will get the oracle and the plugins binary, and set the default values accordingly. Do we expect them to just download the pre-compiled binaries from the release? Then I would set the default values according to the folder structure of the `autonity-oracle.tgz` [attached to the release](https://github.com/autonity/autonity-oracle/releases/tag/v0.1.2).

Some feedback on the [sample config file](https://github.com/autonity/autonity-oracle/blob/master/config/plugins-conf.yml):
- Are those api keys real?
- is there a reason for setting the default refresh period to 3600s?

Additionally, It would be nice to have:
- a `--version` option to retrieve the oracle version
- a verbosity option to set the verbosity of the logger

**Comment by lorenzo-dev1** [comment]
Also the oracle crashes if the autonity client is closed. We should probably handle the connection closure gracefully

**Comment by Jason-Zhangxin-Chen** [comment]
To be closed by https://github.com/autonity/autonity-oracle/pull/4

**Comment by lorenzo-dev1** [comment]
>  Those api keys are free keys applied from data providers for the integration test, it does not promise service quality.

Ok got it, if we applied for them, then I would still remove them from the readme. Otherwise anyone can use them and reduce our quotas... We can just put a random string instead or change a few digits for each key.

>  Since the data providers limit the access rate with different QoS by the pricing, we set an optimistic value 1 hours. The end user can tune this interval base on their QoS.

I understand the rate limiting set by providers, however I think this might have a detrimental effect to the quality of our Oracle service. Because I think most people will just use the default configuration at first, however we need to fetch prices at least every 30s (as the oracle rounds are 30s). Therefore I would put a default frequency << 30s, and let the user deal with rate limitations.

Otherwise people might think fetching prices every hour is the behaviour we want.

Or am I missing something here?

**Comment by lorenzo-dev1** [comment]
@Jason-Zhangxin-Chen I think that the points I made in https://github.com/autonity/autonity-oracle/issues/3#issuecomment-1827604619 are still valid, what is your opinion on them?

**Comment by Jason-Zhangxin-Chen** [comment]
> @Jason-Zhangxin-Chen I think that the points I made in [#3 (comment)](https://github.com/autonity/autonity-oracle/issues/3#issuecomment-1827604619) are still valid, what is your opinion on them?

I think these are good idea as well, I will create issue to implement it. Thanks Lorenzo.
