### ISSUE TITLE
Configuration options - should `SYMBOLS` be deprecated?

### ISSUE THREAD

**Issue by cmjc** [autonity/autonity-oracle#7]
## Context

At present the SYMBOLS for a testnet are set in the client in the config, e.g.

https://github.com/autonity/autonity/blob/4504e8acccca8ab65f8aba63a2674f51bc6250e6/params/protocol_contracts.go#L23C1-L23C1

```golang
OracleInitialSymbols       = []string{"AUD-USD", "CAD-USD", "EUR-USD", "GBP-USD", "JPY-USD", "SEK-USD", "ATN-USD", "NTN-USD", "NTN-ATN"}
```

This default oracle config is then picked up by the oracle server, which is why it does not need to be set in your config when you are running the oracle server.  I.E.: it is not required, which is clear in the README under [Configuration](https://github.com/autonity/autonity-oracle#configuration):

>
>Values that can be configured by using environment variables:
>
| **Env Variable** | **Required?** | **Meaning** | **Default Value**                                                                                    | **Valid Options** |
|----------------------------|---------------|---------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------|---------------------------------------------------------|
| `SYMBOLS` | No | The symbols that the oracle component collects data points for | "AUD-USD,CAD-USD,EUR-USD,GBP-USD,JPY-USD,SEK-USD,ATN-USD,NTN-USD,NTN-ATN"         

## Question

- What is the scenario for needing to set `SYMBOLS` in config?  What is or are the scenario(s) where an oracle server operator would want to set symbols in their local config? The symbol set is auto-detected by the oracle server, so it's not needed for connection to a Public TestNet.
- When would symbols be different? As a validator you supply all not some of the symbol set.
- Local Testnet. To set your own Symbols and ASM config in a local testnet makes sense, but is there really a scenario where this would be realistic?

**Comment by Jason-Zhangxin-Chen** [comment]
@cmjc  I think we can remove this configuration from oracle server since those symbols are overwrite once the oracle server connect to the L1 network.

**Comment by cmjc** [comment]
OK, thanks @Jason-Zhangxin-Chen @yazzaoui fyi
