### ISSUE TITLE
Override default refresh rate to 1 hour in example config

### ISSUE THREAD

**Issue by spenot09** [autonity/autonity-oracle#9]
Default values for the oracle have now been set to a lower refresh period which are too low for some of the free tiers in the forex APIs we are supplying.

I propose that in the example config (that most people will likely use as the Docs links to it) we include an entry to override the default refresh rate to 1 hour, in order to allow validators to use the free tiers without hitting their API limits.

I.e. in this file https://github.com/autonity/autonity-oracle/blob/master/config/plugins-conf.yml the entries follow a pattern something like:

```
#  - name: forex_currencyfreaks              # required, it is the plugin file name in the plugin directory.
#    key: 175aab9e47e54790bf6d502c48407c10   # required, visit https://currencyfreaks.com to get your key, and replace it.
#    refresh: 3600                           # optional, recommended for testnets in order to not exceed the free tier API limits.

```

**Comment by lorenzo-dev1** [comment]
The default rate was changed from 3600 to 30s based on my suggestion (see reasons in https://github.com/autonity/autonity-oracle/issues/3#issuecomment-1827604619).

I am open to change my mind but I think we should set the defaults of the oracle based upon the needs of our protocol, not based upon the API limits of third parties.
